### ISSUE TITLE
Http response code 400

### ISSUE THREAD

**Issue by ulshamim** [xroot/laravel-paypalpayment#32] opened 2015-01-15 10:39 UTC
At the time of payment I got an error:
Got Http response code 400 when accessing https://api.sandbox.paypal.com/v1/payments/payment.

**Comment by xroot** [comment] 2015-01-15 13:52
run composer update ; then make sure to pass your client Id and ckient secret key to api context  example: Paypalpayment::ApiContext($this->_ClientId, $this->_ClientSecret);
Also check your log for further information.

**Comment by ulshamim** [comment] 2015-01-16 10:34
Still same error and this is in log file.

[16-01-2015 10:19:50] PayPal\Core\PPHttpConnection: INFO: POST https://api.sandbox.paypal.com/v1/payments/payment
[16-01-2015 10:19:50] PayPal\Core\PPHttpConnection: FINE: Content-Type: application/json
[16-01-2015 10:19:50] PayPal\Core\PPHttpConnection: FINE: User-Agent: PayPalSDK/PayPal-PHP-SDK 0.15.1 (lang=PHP;v=5.5.9;bit=32;os=Windows_NT_6.1;machine=i586;openssl=1.0.1e;curl=7.30.0)
[16-01-2015 10:19:50] PayPal\Core\PPHttpConnection: FINE: Authorization: Bearer A015Sl0FJ2YfDg4WUcfc1BRpsVgk7TFBMWC-6JxTs391STo
[16-01-2015 10:19:50] PayPal\Core\PPHttpConnection: FINE: PayPal-Request-Id: ITOBUZ05-PC4588142140357844187
[16-01-2015 10:19:50] PayPal\Core\PPHttpConnection: FINE: Payload : {"intent":"sale","payer":{"payment_method":"credit_card","funding_instruments":[{"credit_card":{"type":"visa","number":"4758411877817150","expire_month":"05","expire_year":"2019","cvv2":"456","first_name":"Joe","last_name":"Shopper"}}]},"transactions":[{"amount":{"currency":"USD","total":"20.00","details":{"shipping":"1.20","tax":"1.30","subtotal":"17.50"}},"item_list":{"items":[{"name":"Ground Coffee 40 oz","description":"Ground Coffee 40 oz","currency":"USD","quantity":1,"tax":"0.30","price":"7.50"},{"name":"Granola bars","description":"Granola Bars with Peanuts","currency":"USD","quantity":5,"tax":"0.20","price":"2.00"}]},"description":"Payment description","invoice_number":"54b8e5bab0b1d"}]}

[16-01-2015 10:19:53] PayPal\Core\PPHttpConnection: INFO: Invalid or no certificate authority found - Retrying using bundled CA certs file
[16-01-2015 10:20:01] PayPal\Core\PPHttpConnection: FINE: Response : {"name":"UNKNOWN_ERROR","message":"An unknown error has occurred","information_link":"https://developer.paypal.com/webapps/developer/docs/api/#UNKNOWN_ERROR","debug_id":"3a83bf2d5ae70"}

**Comment by xroot** [comment] 2015-01-16 15:30
Could you please share with me the code that process the payment .

**Comment by ulshamim** [comment] 2015-01-16 15:36
For testing I have used your code with my client ID and secrete code. Also I have I have used only 2 function for testing construct and create function. This is my controller:

~~~
<?php

class PaypalPaymentController extends BaseController {

    private $_apiContext;
    private $_ClientId = 'AVGu9BCDoNP1iHnRDdikIATnfmBg1P2GQNfvW1X7nmBQ88o6TSL2gwJ2ZLuR';
    private $_ClientSecret = 'EGEYiBBFMnG7cqIKFojQAriCsMFQ2fRAd9bHnqe4bzb-Z3Mmwqh3v6txMhzm';

    public function __construct() {

        // ### Api Context
        // Pass in a `ApiContext` object to authenticate
        // the call. You can also send a unique request id
        // (that ensures idempotency). The SDK generates
        // a request id if you do not pass one explicitly.

        $this->_apiContext = Paypalpayment::ApiContext($this->_ClientId, $this->_ClientSecret);

        // Uncomment this step if you want to use per request
        // dynamic configuration instead of using sdk_config.ini

        $this->_apiContext->setConfig(array(
            'mode' => 'sandbox',
            'service.EndPoint' => 'https://api.sandbox.paypal.com',
            'http.ConnectionTimeOut' => 30,
            'log.LogEnabled' => true,
            'log.FileName' => __DIR__ . '/../PayPal.log',
            'log.LogLevel' => 'FINE'
        ));
    }

    /*
     * Display form to process payment using credit card
     */

    public function create() {
        return View::make('payment.order');
    }

    /*
     * Process payment using credit card
     */

    public function store() {
        // ### Address
        // Base Address object used as shipping or billing
        // address in a payment. [Optional]
        $addr = Paypalpayment::address();
        $addr->setLine1("3909 Witmer Road");
        $addr->setLine2("Niagara Falls");
        $addr->setCity("Niagara Falls");
        $addr->setState("NY");
        $addr->setPostal_code("14305");
        $addr->setCountry_code("US");
        $addr->setPhone("716-298-1822");

        // ### CreditCard
        $card = Paypalpayment::creditCard();
        $card->setType("visa")
                ->setNumber("4758411877817150")
                ->setExpireMonth("05")
                ->setExpireYear("2019")
                ->setCvv2("456")
                ->setFirstName("Joe")
                ->setLastName("Shopper");

        // ### FundingInstrument
        // A resource representing a Payer's funding instrument.
        // Use a Payer ID (A unique identifier of the payer generated
        // and provided by the facilitator. This is required when
        // creating or using a tokenized funding instrument)
        // and the `CreditCardDetails`
        $fi = Paypalpayment::fundingInstrument();
        $fi->setCredit_card($card);

        // ### Payer
        // A resource representing a Payer that funds a payment
        // Use the List of `FundingInstrument` and the Payment Method
        // as 'credit_card'
        $payer = Paypalpayment::payer();
        $payer->setPaymentMethod("credit_card")
                ->setFundingInstruments(array($fi));

        $item1 = Paypalpayment::item();
        $item1->setName('Ground Coffee 40 oz')
                ->setDescription('Ground Coffee 40 oz')
                ->setCurrency('USD')
                ->setQuantity(1)
                ->setTax(0.30)
                ->setPrice(7.50);

        $item2 = Paypalpayment::item();
        $item2->setName('Granola bars')
                ->setDescription('Granola Bars with Peanuts')
                ->setCurrency('USD')
                ->setQuantity(5)
                ->setTax(0.20)
                ->setPrice(2);


        $itemList = Paypalpayment::itemList();
        $itemList->setItems(array($item1, $item2));


        $details = Paypalpayment::details();
        $details->setShipping("1.20")
                ->setTax("1.30")
                //total of items prices
                ->setSubtotal("17.50");

        //Payment Amount
        $amount = Paypalpayment::amount();
        $amount->setCurrency("USD")
                // the total is $17.8 = (16 + 0.6) * 1 ( of quantity) + 1.2 ( of Shipping).
                ->setTotal("20.00")
                ->setDetails($details);

        // ### Transaction
        // A transaction defines the contract of a
        // payment - what is the payment for and who
        // is fulfilling it. Transaction is created with
        // a `Payee` and `Amount` types

        $transaction = Paypalpayment::transaction();
        $transaction->setAmount($amount)
                ->setItemList($itemList)
                ->setDescription("Payment description")
                ->setInvoiceNumber(uniqid());

        // ### Payment
        // A Payment Resource; create one using
        // the above types and intent as 'sale'

        $payment = Paypalpayment::payment();

        $payment->setIntent("sale")
                ->setPayer($payer)
                ->setTransactions(array($transaction));

        try {
            // ### Create Payment
            // Create a payment by posting to the APIService
            // using a valid ApiContext
            // The return object contains the status;
            $payment->create($this->_apiContext);
        } catch (\PPConnectionException $ex) {
            return "Exception: " . $ex->getMessage() . PHP_EOL;
            exit(1);
        }

        dd($payment);
    }

}

~~~
This is my route:
Route::resource('payment', 'PaypalPaymentController');

**Comment by xroot** [comment] 2015-01-16 15:38
show me your composer json file please

**Comment by ulshamim** [comment] 2015-01-16 15:41
This is the composer.json file:
~~~
{
	"name": "laravel/laravel",
	"description": "The Laravel Framework.",
	"keywords": ["framework", "laravel"],
	"license": "MIT",
	"type": "project",
	"require": {
		"laravel/framework": "4.2.*",
                "redooor/redminportal": "0.1.*@dev",
                "cartalyst/sentry": "2.1.*",
                "anouar/paypalpayment": "1.*",
                "moltin/laravel-cart": "dev-master"

		
	},
	"autoload": {
		"classmap": [
			"app/commands",
			"app/controllers",
			"app/models",
			"app/database/migrations",
			"app/database/seeds",
			"app/tests/TestCase.php"
		]
	},
	"scripts": {
		"post-install-cmd": [
			"php artisan clear-compiled",
			"php artisan optimize"
		],
		"post-update-cmd": [
			"php artisan clear-compiled",
			"php artisan optimize"
		],
		"post-create-project-cmd": [
			"php artisan key:generate"
		]
	},
	"config": {
		"preferred-install": "dist"
	},
	"minimum-stability": "dev",
        "prefer-stable": true
}
~~~

**Comment by xroot** [comment] 2015-01-16 15:43
did you tried to run composer update ...?

**Comment by ulshamim** [comment] 2015-01-16 15:45
Yes I tried 2 times but same result.

**Comment by xroot** [comment] 2015-01-16 15:50
ok one second let me check

**Comment by ulshamim** [comment] 2015-01-16 15:56
OK let me know I am waiting for your reply.. Thanks in advance.

**Comment by xroot** [comment] 2015-01-16 16:33
could you please remove the package entirely and install it again , you may
still have the old version that get installed from you cache

**Comment by xroot** [comment] 2015-01-16 16:44
try this instead : composer update anouar/paypalpayment --prefer-source

**Comment by ulshamim** [comment] 2015-01-17 07:39
Still same issue. First I tried to update the package but it said nothing to install or update then I remove the package and re-install. But same issue.

**Comment by xroot** [comment] 2015-01-17 16:21
send me your controller ,I'll user code and see if it will work

**Comment by ulshamim** [comment] 2015-01-17 18:20
OK. But I sent you PaypalPaymentController.php earlier. OK one more time I send you. Also let me know if you need anything else. This is the PaypalPaymentController.php
~~~

class PaypalPaymentController extends BaseController {

    private $_apiContext;
    private $_ClientId = 'AVGu9BCDoNP1iHnRDdikIATnfmBg1P2GQNfvW1X7nmBQ88o6TSL2gwJ2ZLuR';
    private $_ClientSecret = 'EGEYiBBFMnG7cqIKFojQAriCsMFQ2fRAd9bHnqe4bzb-Z3Mmwqh3v6txMhzm';

    public function __construct() {

        // ### Api Context
        // Pass in a `ApiContext` object to authenticate
        // the call. You can also send a unique request id
        // (that ensures idempotency). The SDK generates
        // a request id if you do not pass one explicitly.

        $this->_apiContext = Paypalpayment::ApiContext($this->_ClientId, $this->_ClientSecret);

        // Uncomment this step if you want to use per request
        // dynamic configuration instead of using sdk_config.ini

        $this->_apiContext->setConfig(array(
            'mode' => 'sandbox',
            'service.EndPoint' => 'https://api.sandbox.paypal.com',
            'http.ConnectionTimeOut' => 3000,
            'log.LogEnabled' => true,
            'log.FileName' => __DIR__ . '/../PayPal.log',
            'log.LogLevel' => 'FINE'
        ));
    }

    /*
     * Display form to process payment using credit card
     */

    public function create() {
        return View::make('payment.order');
    }

    /*
     * Process payment using credit card
     */

    public function store() {
        // ### Address
        // Base Address object used as shipping or billing
        // address in a payment. [Optional]
        $addr = Paypalpayment::address();
        $addr->setLine1("3909 Witmer Road");
        $addr->setLine2("Niagara Falls");
        $addr->setCity("Niagara Falls");
        $addr->setState("NY");
        $addr->setPostal_code("14305");
        $addr->setCountry_code("US");
        $addr->setPhone("716-298-1822");

        // ### CreditCard
        $card = Paypalpayment::creditCard();
        $card->setType("visa")
                ->setNumber("4758411877817150")
                ->setExpireMonth("05")
                ->setExpireYear("2019")
                ->setCvv2("456")
                ->setFirstName("Joe")
                ->setLastName("Shopper");

        // ### FundingInstrument
        // A resource representing a Payer's funding instrument.
        // Use a Payer ID (A unique identifier of the payer generated
        // and provided by the facilitator. This is required when
        // creating or using a tokenized funding instrument)
        // and the `CreditCardDetails`
        $fi = Paypalpayment::fundingInstrument();
        $fi->setCredit_card($card);

        // ### Payer
        // A resource representing a Payer that funds a payment
        // Use the List of `FundingInstrument` and the Payment Method
        // as 'credit_card'
        $payer = Paypalpayment::payer();
        $payer->setPaymentMethod("credit_card")
                ->setFundingInstruments(array($fi));

        $item1 = Paypalpayment::item();
        $item1->setName('Ground Coffee 40 oz')
                ->setDescription('Ground Coffee 40 oz')
                ->setCurrency('USD')
                ->setQuantity(1)
                ->setTax(0.30)
                ->setPrice(7.50);

        $item2 = Paypalpayment::item();
        $item2->setName('Granola bars')
                ->setDescription('Granola Bars with Peanuts')
                ->setCurrency('USD')
                ->setQuantity(5)
                ->setTax(0.20)
                ->setPrice(2);


        $itemList = Paypalpayment::itemList();
        $itemList->setItems(array($item1, $item2));


        $details = Paypalpayment::details();
        $details->setShipping("1.20")
                ->setTax("1.30")
                //total of items prices
                ->setSubtotal("17.50");

        //Payment Amount
        $amount = Paypalpayment::amount();
        $amount->setCurrency("USD")
                // the total is $17.8 = (16 + 0.6) * 1 ( of quantity) + 1.2 ( of Shipping).
                ->setTotal("20.00")
                ->setDetails($details);

        // ### Transaction
        // A transaction defines the contract of a
        // payment - what is the payment for and who
        // is fulfilling it. Transaction is created with
        // a `Payee` and `Amount` types

        $transaction = Paypalpayment::transaction();
        $transaction->setAmount($amount)
                ->setItemList($itemList)
                ->setDescription("Payment description")
                ->setInvoiceNumber(uniqid());

        // ### Payment
        // A Payment Resource; create one using
        // the above types and intent as 'sale'

        $payment = Paypalpayment::payment();

        $payment->setIntent("sale")
                ->setPayer($payer)
                ->setTransactions(array($transaction));

        try {
            // ### Create Payment
            // Create a payment by posting to the APIService
            // using a valid ApiContext
            // The return object contains the status;
            $payment->create($this->_apiContext);
        } catch (\PPConnectionException $ex) {
            return "Exception: " . $ex->getMessage() . PHP_EOL;
            exit(1);
        }

        dd($payment);
    }

}
~~~

**Comment by xroot** [comment] 2015-01-17 21:30
ok let fix this issue now and close it

**Comment by xroot** [comment] 2015-01-17 21:50
the issue is related to your secret and client ID , I have experienced the same error within your keys , but when switched to my own sandbox keys , it worked perfect . login to your paypal sandbox and grap the correct credentials . try it I'm 100% sure . if it fixed let me know to close this issue . thanks

**Comment by ulshamim** [comment] 2015-01-18 15:57
Ya It works. I have used IN account that's why it's not working.

**Comment by xroot** [comment] 2015-01-18 16:20
ok nice

**Closed** 2015-01-18 16:20 UTC

**Comment by kapillohakare** [comment] 2015-04-09 12:47
Hi Ulshamim and Xroot,

Can you, please brief me about IN account? I got the same problem as well. I checked the keys and updated composer as well. I am working on my local machine. I got same error as Ulshamim.

Thanks in advance.

**Comment by arvind132** [comment] 2015-09-02 16:24
I have used us account, but still i got 400 response error in my localhost. could you please tell me what will be the mistake?

**Comment by jeraldpunx** [comment] 2016-03-30 14:56
Help me, I got this too. The keys are correct and updated the composer too. Need help please.

**Comment by rameshsrinivasan** [comment] 2016-10-17 09:16
What is mean IN account? Please help me, I also facing same issue.
